---
title: "Ranking"
output: html_notebook
---

```{r}
library(readr)
library(stringr)
library(dplyr)
library(nleqslv)

`%+%` <- function(x, y){
  paste0(x, y)
}

fn <- function(x){
  x <- x[-length(x)]
  y <- numeric(n_teams)
  denom <- numeric(n_teams)
  for(i in 1:n_teams){
    d <- numeric(n_teams)  # tworzy zera (na pewno będzie jedno zero - dla j==i)
    for(j in 1:n_teams){
      if(j != i){
        d[j] <- matches_matrix[i, j] / (x[i] + x[j])
      }
    }
    denom[i] <- sum(d)
  }
  
  y = number_of_matches_played * average_scores / denom
  
  return(c(y-x, sum(y)-1))
}


matr <- function(matches.f=matches.f){
  players <- unique(c(matches.f$team1, matches.f$team2))
  
  matches_matrix <- matrix(0, nrow=length(players), ncol=length(players), dimnames=list(players, players))
  results_matrix <- matrix(0, nrow=length(players), ncol=length(players), dimnames=list(players, players))
  for(player1 in players){
    for(player2 in players){
      matches.f %>% 
        filter(team1==player1 & team2==player2) ->
        m.filt
      matches_matrix[player1, player2] <- m.filt %>% dim %>% `[`(1)
      results_matrix[player1, player2] <- m.filt %>% mutate(is_wining=score1 > score2) %>% pull(is_wining) %>% sum
  
      matches.f %>% 
        filter(team1==player2 & team2==player1) ->
        m.filt
      matches_matrix[player1, player2] <- matches_matrix[player1, player2] + m.filt %>% dim %>% `[`(1)
      results_matrix[player1, player2] <- results_matrix[player1, player2] + m.filt %>% mutate(is_wining=score1 < score2) %>% pull(is_wining) %>% sum
    }
  }
  
  number_of_matches_played <- apply(matches_matrix, 1, sum)  # m
  average_scores <- apply(results_matrix, 1, sum) / number_of_matches_played # s
  
  list(
    "matches_matrix"=matches_matrix,
    "results_matrix"=results_matrix,
    "number_of_matches_played"=number_of_matches_played,
    "average_scores"=average_scores,
    "players"=players)
}
  
get_scores <- function(strength1, strength2){
  out <- tibble("score1"=numeric(), "score2"=numeric())

  for(i in 1:length(strength1)){
    diff <- abs(strength1[i] - strength2[i]) + .1
    stronger_team <- sample(0:1, 1, prob=(c(.1, diff))) # aby silniejsza drużyna miała więcej zwycięstw
    if(strength1[i] > strength2[i]){
      out %>% 
        bind_rows(tibble("score1"=stronger_team, "score2"=abs(stronger_team - 1))) ->
        out
    }else{
      out %>% 
        bind_rows(tibble("score1"=abs(stronger_team - 1), "score2"=stronger_team)) ->
        out
    }
  }
  out
}

```

Rzeczywiste dane
```{r}
read_csv2("mecze-towarzyski-2017-pilka-nozna.csv", col_names = c("date", "team1", "team2", "score")) %>% 
  mutate(score1=as.integer(str_match(score, "(\\d*):")[,2])) %>% 
  mutate(score2=as.integer(str_match(score, ":(\\d*)")[,2])) %>% 
  filter(score1!=score2) %>% 
  select(-score) ->
  matches
# https://www.flashscores.co.uk/football/world/world-cup-2014/results/
read_csv("world_cup", col_names = c("team1", "team2", "score"), comment="#", col_types='ccc') %>% 
  mutate(score1=as.integer(str_match(score, "(\\d*):")[,2])) %>% 
  mutate(score2=as.integer(str_match(score, ":(\\d*)")[,2])) %>% 
  select(-score) ->
  matches.f
```


```{r}
m <- matr(matches.f)

matches_matrix <- m$matches_matrix
results_matrix <- m$results_matrix
number_of_matches_played <- m$number_of_matches_played
average_scores <- m$average_scores
players <- m$players

n_teams <- length(players)

sm=F  # aby wymusić dobre rozwiązanie
fv=T
d=T
# nie znajduje takiego rozwiązania
while(any(fv) | sm | d){
  x = runif(n_teams+1) * 10
  # x = rnorm(n_teams+1) * 100
  ans = nleqslv(x, fn, control = list("allowSingular"=T))
  
  sm <- sum(ans$x[-length(ans$x)]) < 0.9  # aby wymusić dobre rozwiązanie
  d <- any(ans$x[-length(ans$x)] < 0)
  fv <- abs(ans$fvec) > 1e-8
}
ans
players[order(-log(ans$x))]
```

# Symulacja
```{r}
n_matches <- 30
teams <- LETTERS[1:5]
n_teams <-  length(teams)

strength <- seq(0.1, 1, length.out=n_teams)  # A najsłabsza, następnie B itd
names(strength) <- teams

team1 <- sample(teams, n_matches, replace=T)
team2 <- sample(teams, n_matches, replace=T)
 
tibble("team1"=team1,
       "team2"=team2) %>% 
  bind_cols(get_scores(strength[team1], strength[team2])) %>%
  filter(team1!=team2) %>%
  filter(score1!=score2) ->
  matches.f

m <- matr(matches.f)

matches_matrix <- m$matches_matrix
results_matrix <- m$results_matrix
number_of_matches_played <- m$number_of_matches_played
average_scores <- m$average_scores
players <- m$players

sm=0
fv=T
while(any(fv)){
  x = runif(n_teams+1) * 1
  # x = rnorm(n_teams+1) * 100
  ans = nleqslv(x, fn, control = list("allowSingular"=T))#, jac=jac)
  
  sm <- sum(ans$x[-length(ans$x)])
  fv <- abs(ans$fvec) > 1e-8
}
sum(ans$x[-length(ans$x)])
ans$message
players[order(-log(ans$x))]

```

Symulacja - układ równań do wolframa
```{r}
n_matches <- 100
teams <- LETTERS[1:2]
n_teams <-  length(teams)

strength <- seq(0.1, 1, length.out=n_teams)  # A najsłabsza
names(strength) <- teams

team1 <- sample(teams, n_matches, replace=T)
team2 <- sample(teams, n_matches, replace=T)
 
tibble("team1"=team1,
       "team2"=team2) %>% 
  bind_cols(get_scores(strength[team1], strength[team2])) %>%
  filter(team1!=team2) %>%
  filter(score1!=score2) ->
  matches.f

m <- matr(matches.f)

matches_matrix <- m$matches_matrix
results_matrix <- m$results_matrix
number_of_matches_played <- m$number_of_matches_played
average_scores <- m$average_scores
players <- m$players


x <- teams
y <- numeric(n_teams)
denom <- character(n_teams)
for(i in 1:n_teams){
  d <- rep("0", n_teams)  # tworzy zera (na pewno będzie jedno zero - dla j==i)
  for(j in 1:n_teams){
    if(j != i){
      d[j] <- paste0(matches_matrix[i, j], "/(", x[i], "+", x[j], ")")
    }
  }
  denom[i] <- paste0(d, collapse = "+")
}

y = paste0(number_of_matches_played * average_scores, "/(",  denom, ")")
z <- paste(players, y, sep="==", collapse=", ")
zz <- paste0(z, ", ", paste(teams, collapse="+"), "==1")

cat(paste0("{",zz,"}"))
```

Bruteforce
```{r}
m <- matr(read_tsv("dane"))
matches_matrix <- m$matches_matrix
results_matrix <- m$results_matrix
number_of_matches_played <- m$number_of_matches_played
average_scores <- m$average_scores
players <- m$players

n_teams=3
fn2 <- function(x){
  y <- numeric(n_teams)
  denom <- numeric(n_teams)
  for(i in 1:n_teams){
    d <- numeric(n_teams)  # tworzy zera (na pewno będzie jedno zero - dla j==i)
    for(j in 1:n_teams){
      if(j != i){
        d[j] <- matches_matrix[i, j] / (x[i] + x[j])
      }
    }
    denom[i] <- sum(d)
  }
  
  y = number_of_matches_played * average_scores / denom
  
  return(c(y-x))
}

tic()
x <- data.frame("x"=rep(seq(0, 1, 0.002), each=501*501), "y"=rep(seq(0, 1, 0.002), each=501), "z"=seq(0, 1, 0.002))
toc()
x %>% 
  filter(x+y+z==1) ->
  y
apply(y, 1, fn2) %>%
  t %>% 
  tbl_df %>% 
  mutate(sum=A+B+C) %>% 
  filter(A>=0 & B>=0 & C>=0) %>% 
  filter(sum < 0.5) ->
  res
```


# Least squares
```{r}
fnl <- function(x){
  # x <- x[-length(x)]
  out <- 0
  for(i in 1:length(x)){
    for(j in 1:length(x)){
      out <- out + matches_matrix[i, j] * (D[i, j] - (x[i] - x[j]))^2
    }
  }
  out <- out + abs(sum(x))*10000000
  return(out)
}


fnl_wolfram <- function(x){
  # x <- x[-length(x)]
  out <- ""
  for(i in 1:length(x)){
    for(j in 1:length(x)){
      if(i != j & matches_matrix[i, j] != 0){
        out <- out %+% "+" %+% matches_matrix[i, j] %+% "*" %+% "(" %+% D[i, j] %+% "-" %+% x[i] %+% "+" %+% x[j] %+% ")^2"
      }
    }
  }
  # out <- out + abs(sum(x))*1e15
  return(out)
}
(w <- fnl_wolfram(players))
w <- str_replace_all(w, "Germany", "A")
w <- str_replace_all(w, "Argentina", "B")
w <- str_replace_all(w, "Netherlands", "C")
w <- str_replace_all(w, "Brazil", "D")
w <- str_replace_all(w, "Costa Rica", "E")
w <- str_replace_all(w, "Belgium", "F")
w <- str_replace_all(w, "Colombia", "G")
w <- str_replace_all(w, "France", "H")
w
w <- str_replace_all(w, "\\+1\\*\\(", "+(")
w <- str_replace_all(w, "0\\-", "\\-")
w
```


```{r}
n_matches <- 7
teams <- LETTERS[1:3]
n_teams <-  length(teams)

strength <- seq(0.1, 1, length.out=n_teams)  # A najsłabsza
names(strength) <- teams

team1 <- sample(teams, n_matches, replace=T)
team2 <- sample(teams, n_matches, replace=T)
 
tibble("team1"=team1,
       "team2"=team2) %>% 
  bind_cols(get_scores(strength[team1], strength[team2])) %>% 
  filter(team1!=team2) %>%
  filter(score1!=score2) ->
  matches.f

m <- matr(matches.f)
matches_matrix <- m$matches_matrix
results_matrix <- m$results_matrix
number_of_matches_played <- m$number_of_matches_played
average_scores <- m$average_scores
players <- m$players
n_teams <- length(players)

D <- (results_matrix - t(results_matrix)) %*% solve(matches_matrix)

results_matrix
players
(ans <- optim(rep(1, n_teams), fnl, control = list("maxit"=5000)))
sum(ans$par)
players[order(ans$par)] # od najsilniejszej do najsłabszej
```










