---
title: "R Notebook"
output: html_notebook
---

```{r rec_bucholz_function}
#Recursive Buchalz
ranking <- function(tournament){ # tournament odpowiada macierzy A z artyułu
  n <- dim(tournament)[1]
  
  matches_matrix <- tournament + t(tournament) # macierz M
  matches_sums <- rowSums(matches_matrix) # wektor m
  scores <- rowSums(tournament, na.rm = TRUE)/matches_sums #wektor s
  
  matches_centered <- matches_matrix/matches_sums - diag(n) #Macierz (M z kreską) - I
  scores_moved <- scores - 0.5 #wektor (s z daszkiem)
  
  #Dodajemy poniżej warunek, że mają się sumować do zera w następujący sposób:
  # dodajemy wiersz jedynek na dole (będzie sumował wszystie wyrazy) i 0 na końcu wyników (żeby sumowłąo się do 0). Żeby macierz była kwadratowa dorzucamy wektor jedynek po prawej (będą mnożone przez to zero więc to może byc cokolwiek różnego od zera)
  matches_centered <- rbind(matches_centered, rep(1, n))
  matches_centered <- cbind(matches_centered, rep(1, n+1))
  scores_moved <- c(scores_moved, 0)
  
  solve(matches_centered, -scores_moved)[1:n]
}
```

```{r tests}
#Macierze z artykułu

#Example 4.2
#A <- matrix(c(0, 5, 15, 5,5, 0, 5, 15, 5, 5, 0, 7, 5, 5, 3, 0), nrow = 4, byrow = TRUE) 
A <- matrix(c(0, 10, 9, 7, 10, 0, 9, 6, 1, 1, 0, 1, 3, 4, 19, 0), nrow = 4, byrow = TRUE)

#Example 6.1
#A <- matrix(c(0, 1, 1, 1, 2, 0, 1, 1, 1, 1, 0, 2, 1, 1, 1, 0), nrow = 4, byrow = TRUE)
#A <- matrix(c(0, 1, 1, 2, 2, 0, 1, 1, 1, 1, 0, 2, 1, 1, 1, 0), nrow = 4, byrow = TRUE) 


2*ranking(A)
```

